version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id

  - name: stg_orders
    columns:
      - name: order_id
      - name: status

  - name: stg_payments
    columns:
      - name: payment_id
      - name: payment_method
